# Your Name or Company
title: Francesca Hart

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist and home maker, Francesca Hart.

# A brief blurb about yourself
content: BLAH BLAH BLAH BLAH BLAH

# Half layout options
half_side: left
half_image: woman-half.jpg

# Add your social links
social:
  - platform: github
    url: https://github.com/BLAH
  - platform: facebook
    url: https://facebook.com/BLAH
  - platform: twitter
    url: https://twitter.com/BLAH
  - platform: linkedin
    url: BLAH

# General settings
url: https://francescahart.com/
baseurl: ""
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-" # google analytics tracking
permalink: pretty

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
